baseURL = 'https://industrial-tft.com/'
languageCode = 'en-us'
title = 'Industrial TFT Display'

[pagination]
  pagerSize = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
